apiVersion: v1
kind: Pod
metadata:
  name: spacy-pod
  namespace: recommeddit
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: spacy-pod
    image: mehir123/spacy:latest
    command: ["sh", "-c", "sleep infinity"]
    resources:
      limits:
        memory: 12Gi
        cpu: 2
        nvidia.com/gpu: 1
        ephemeral-storage: 5Gi    
      requests:
        memory: 12Gi
        cpu: 2
        nvidia.com/gpu: 1
        ephemeral-storage: 5Gi    
    volumeMounts:
    - mountPath: /tempstore
      name: tempstore
  volumes:
    - name: tempstore
      emptyDir: {}
