apiVersion: batch/v1
kind: Job
metadata:
  name: spacy-job0
  namespace: recommeddit
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
      containers:
      - name: spacy-pod
        image: mehir123/spacy:latest
        command: ["/bin/sh"]
        args: ["-c", "wandb agent mehir/ner_test/crqzrnku & wandb agent mehir/ner_test/crqzrnku && sleep 10"]
        resources:
          limits:
            memory: 10Gi
            cpu: 2
            nvidia.com/gpu: 1
            ephemeral-storage: 5Gi    
          requests:
            memory: 10Gi
            cpu: 2
            nvidia.com/gpu: 1
            ephemeral-storage: 5Gi    
        volumeMounts:
        - mountPath: /tempstore
          name: tempstore
      volumes:
        - name: tempstore
          emptyDir: {}
      restartPolicy: Never     
  backoffLimit: 4
